import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
// import { ClerkProvider} from '@clerk/nextjs'
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <header>
        {/* <SignedOut> */}
              {/* <SignInButton /> */}
            {/* </SignedOut> */}
            {/* <SignedIn> */}
              {/* <UserButton /> */}
            {/* </SignedIn> */}
        </header>
        <main>
          {children}
        </main>
        {/* {children} */}
        {/* {<Header></Header>} */}
        </body>
    </html>
    </ClerkProvider>
  );
}
